create table if not exists public.giveaways (
  id uuid primary key,
  workspace_id text not null,
  name text not null default 'Untitled giveaway',
  platform text not null,
  status text not null default 'open',
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  giveaway_id uuid not null references public.giveaways(id) on delete cascade,
  participant_key text not null,
  name text not null,
  role text not null default 'Viewer',
  weight integer not null default 1,
  created_at timestamptz not null default now(),
  unique (giveaway_id, participant_key)
);

create index if not exists participants_giveaway_idx on public.participants(giveaway_id, id);
create index if not exists participants_workspace_idx on public.participants(workspace_id, giveaway_id);

create table if not exists public.draws (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  giveaway_id uuid not null references public.giveaways(id) on delete cascade,
  platform text not null,
  winners jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.giveaways enable row level security;
alter table public.participants enable row level security;
alter table public.draws enable row level security;
